In [65]:
import pandas as pd

file_path = r"\\wsl.localhost\Ubuntu-24.04\home\shreya\sim\data\raw\ncbi\pubmed_openfda\a751bc3c-aad9-4b0a-ba77-c9ca9cfcef14\records.jsonl"

df_one = pd.read_json(file_path, lines=True)

print(df_one.shape)
df_one.head()

(7108, 11)

,pmid,title,abstract,authors,journal,pub_date,doi,format,source_jsonl_line,source_retstart,source_efetch_batch
0,39701733.0,[Analysis of inorganic elements in Bambusae Co...,Inductively coupled plasma mass spectrometry w...,"[Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2024 Oct,10.19540/j.cnki.cjcmm.20240713.103,pubmed_xml,1,0,0
1,38417599.0,Chemical components with antibacterial propert...,ETHNOPHARMACOLOGICAL RELEVANCE: Sanchen powder...,"[Zhao, Yueying, Xi, Cheng, Liu, Donghan, Ren, ...",Journal of ethnopharmacology,2024 May 23,10.1016/j.jep.2024.117981,pubmed_xml,1,0,0
2,37351491.0,The genome of the reef-building glass sponge,Well-annotated and contiguous genomes are an i...,"[Francis, Warren R, Eitel, Michael, Vargas, Se...",Royal Society open science,2023 Jun,10.1098/rsos.230423,pubmed_xml,1,0,0
3,37282866.0,[Significance of high expression of C5orf46 in...,"This study aims to investigate the expression,...","[Zhou, Ying-Jia, Liu, Jia-Ming, Liu, Bin, Wang...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2023 May,10.19540/j.cnki.cjcmm.20230117.701,pubmed_xml,1,0,0
4,36350323.0,Breast Abscess Healing with Homoeopathy: A Cas...,CONTEXT: Breast abscess is the most common com...,"[Kotwani, Eena, Aphale, Parth, Sharma, Dharmen...",Alternative therapies in health and medicine,2023 May,None,pubmed_xml,1,0,0

In [66]:
df_one.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7108 entries, 0 to 7107
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pmid                 7104 non-null   float64
 1   title                7033 non-null   object
 2   abstract             6793 non-null   object
 3   authors              7108 non-null   object
 4   journal              7104 non-null   object
 5   pub_date             7097 non-null   object
 6   doi                  7017 non-null   object
 7   format               7108 non-null   object
 8   source_jsonl_line    7108 non-null   int64
 9   source_retstart      7108 non-null   int64
 10  source_efetch_batch  7108 non-null   int64
dtypes: float64(1), int64(3), object(7)
memory usage: 611.0+ KB

In [67]:
import pandas as pd

file_path = r"\\wsl.localhost\Ubuntu-24.04\home\shreya\sim\data\raw\ncbi\pubmed_openfda\a751bc3c-aad9-4b0a-ba77-c9ca9cfcef14\pages.jsonl"

df = pd.read_json(file_path, lines=True)

print(df.shape)
df.head()

(1475, 7)

,drug_name,query,retstart,retmax,ids,esearch,efetch_responses
0,silicea,(silicea[Title/Abstract]) AND (pharmacology OR...,0,10,"[39701733, 38417599, 37351491, 37282866, 36350...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
1,titanium dioxide,(titanium dioxide[Title/Abstract]) AND (pharma...,0,10,"[41977548, 41976204, 41970853, 41969534, 41945...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
2,ethylhexyl methoxycinnamate,(ethylhexyl methoxycinnamate[Title/Abstract]) ...,0,10,"[41985167, 41915798, 41548346, 41304479, 41151...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
3,zinc oxide,(zinc oxide[Title/Abstract]) AND (pharmacology...,0,10,"[41985804, 41984425, 41977622, 41977548, 41976...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
4,povidone-iodine,(povidone-iodine[Title/Abstract]) AND (pharmac...,0,10,"[41991252, 41905628, 41891504, 41881430, 41871...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."

In [68]:
df.columns

Index(['drug_name', 'query', 'retstart', 'retmax', 'ids', 'esearch',
       'efetch_responses'],
      dtype='object')

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   drug_name         1475 non-null   object
 1   query             1475 non-null   object
 2   retstart          1475 non-null   int64
 3   retmax            1475 non-null   int64
 4   ids               1475 non-null   object
 5   esearch           1475 non-null   object
 6   efetch_responses  1475 non-null   object
dtypes: int64(2), object(5)
memory usage: 80.8+ KB

In [70]:
df.drop(columns=['retmax'], inplace=True)

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475 entries, 0 to 1474
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   drug_name         1475 non-null   object
 1   query             1475 non-null   object
 2   retstart          1475 non-null   int64
 3   ids               1475 non-null   object
 4   esearch           1475 non-null   object
 5   efetch_responses  1475 non-null   object
dtypes: int64(1), object(5)
memory usage: 69.3+ KB

In [72]:
df['esearch'][0]

{'header': {'type': 'esearch', 'version': '0.3'},
 'esearchresult': {'count': '9',
  'retmax': '9',
  'retstart': '0',
  'idlist': ['39701733',
   '38417599',
   '37351491',
   '37282866',
   '36350323',
   '35951064',
   '33348418',
   '32407349',
   '31454832'],
  'translationset': [{'from': 'pharmacology',
    'to': '"pharmacology"[MeSH Terms] OR "pharmacology"[All Fields] OR "pharmacologies"[All Fields] OR "pharmacology"[Subheading]'},
   {'from': 'toxicity',
    'to': '"toxic"[All Fields] OR "toxical"[All Fields] OR "toxically"[All Fields] OR "toxicant"[All Fields] OR "toxicant\'s"[All Fields] OR "toxicants"[All Fields] OR "toxicated"[All Fields] OR "toxication"[All Fields] OR "toxicities"[All Fields] OR "toxicity"[Subheading] OR "toxicity"[All Fields] OR "toxicity\'s"[All Fields] OR "toxics"[All Fields]'},
   {'from': 'mechanism',
    'to': '"mechanism"[All Fields] OR "mechanisms"[All Fields]'}],
  'querytranslation': '"silicea"[Title/Abstract] AND ("pharmacology"[MeSH Terms] OR "pharmacology"[All Fields] OR "pharmacologies"[All Fields] OR "pharmacology"[MeSH Subheading] OR ("toxic"[All Fields] OR "toxical"[All Fields] OR "toxically"[All Fields] OR "toxicant"[All Fields] OR "toxicant s"[All Fields] OR "toxicants"[All Fields] OR "toxicated"[All Fields] OR "toxication"[All Fields] OR "toxicities"[All Fields] OR "toxicity"[MeSH Subheading] OR "toxicity"[All Fields] OR "toxicity s"[All Fields] OR "toxics"[All Fields]) OR "adverse effects"[All Fields] OR ("mechanism"[All Fields] OR "mechanisms"[All Fields])) AND 2020/01/01:2026/12/31[Date - Publication]'}}

In [73]:
df['esearch'][1]

{'header': {'type': 'esearch', 'version': '0.3'},
 'esearchresult': {'count': '2506',
  'retmax': '10',
  'retstart': '0',
  'idlist': ['41977548',
   '41976204',
   '41970853',
   '41969534',
   '41945869',
   '41943320',
   '41936886',
   '41936430',
   '41933561',
   '41904822'],
  'translationset': [{'from': 'pharmacology',
    'to': '"pharmacology"[MeSH Terms] OR "pharmacology"[All Fields] OR "pharmacologies"[All Fields] OR "pharmacology"[Subheading]'},
   {'from': 'toxicity',
    'to': '"toxic"[All Fields] OR "toxical"[All Fields] OR "toxically"[All Fields] OR "toxicant"[All Fields] OR "toxicant\'s"[All Fields] OR "toxicants"[All Fields] OR "toxicated"[All Fields] OR "toxication"[All Fields] OR "toxicities"[All Fields] OR "toxicity"[Subheading] OR "toxicity"[All Fields] OR "toxicity\'s"[All Fields] OR "toxics"[All Fields]'},
   {'from': 'mechanism',
    'to': '"mechanism"[All Fields] OR "mechanisms"[All Fields]'}],
  'querytranslation': '"titanium dioxide"[Title/Abstract] AND ("pharmacology"[MeSH Terms] OR "pharmacology"[All Fields] OR "pharmacologies"[All Fields] OR "pharmacology"[MeSH Subheading] OR ("toxic"[All Fields] OR "toxical"[All Fields] OR "toxically"[All Fields] OR "toxicant"[All Fields] OR "toxicant s"[All Fields] OR "toxicants"[All Fields] OR "toxicated"[All Fields] OR "toxication"[All Fields] OR "toxicities"[All Fields] OR "toxicity"[MeSH Subheading] OR "toxicity"[All Fields] OR "toxicity s"[All Fields] OR "toxics"[All Fields]) OR "adverse effects"[All Fields] OR ("mechanism"[All Fields] OR "mechanisms"[All Fields])) AND 2020/01/01:2026/12/31[Date - Publication]'}}

In [74]:
df['efetch_responses'][0]

['<?xml version="1.0" ?>\n<!DOCTYPE PubmedArticleSet PUBLIC "-//NLM//DTD PubMedArticle, 1st January 2025//EN" "https://dtd.nlm.nih.gov/ncbi/pubmed/out/pubmed_250101.dtd">\n<PubmedArticleSet>\n<PubmedArticle><MedlineCitation Status="MEDLINE" Owner="NLM" IndexingMethod="Automated"><PMID Version="1">39701733</PMID><DateCompleted><Year>2024</Year><Month>12</Month><Day>19</Day></DateCompleted><DateRevised><Year>2024</Year><Month>12</Month><Day>19</Day></DateRevised><Article PubModel="Print"><Journal><ISSN IssnType="Print">1001-5302</ISSN><JournalIssue CitedMedium="Print"><Volume>49</Volume><Issue>20</Issue><PubDate><Year>2024</Year><Month>Oct</Month></PubDate></JournalIssue><Title>Zhongguo Zhong yao za zhi = Zhongguo zhongyao zazhi = China journal of Chinese materia medica</Title><ISOAbbreviation>Zhongguo Zhong Yao Za Zhi</ISOAbbreviation></Journal><ArticleTitle>[Analysis of inorganic elements in Bambusae Concretio Silicea based on inductively coupled plasma mass spectrometry].</ArticleTitle><Pagination><StartPage>5497</StartPage><EndPage>5504</EndPage><MedlinePgn>5497-5504</MedlinePgn></Pagination><ELocationID EIdType="doi" ValidYN="Y">10.19540/j.cnki.cjcmm.20240713.103</ELocationID><Abstract><AbstractText>Inductively coupled plasma mass spectrometry was employed to determine the content of 25 inorganic elements in Bambusae Concretio Silicea, and the elemental fingerprint was established according to the element content. SPSS 20.0 and SIMCA 14.1 were used for chemometric analysis. A total of 25 elements were detected in Bambusae Concretio Silicea, including boron(B), sodium(Na), magnesium(Mg), aluminum(Al), potassium(K), calcium(Ca), scandium(Sc), vanadium(V), chromium(Cr), manganese(Mn), iron(Fe), cobalt(Co), nickel(Ni), copper(Cu), zinc(Zn), gallium(Ga), arsenic(As), selenium(Se), zirconium(Zr), molybdenum(Mo), cadmium(Cd), indium(In), barium(Ba), plumbum(Pb), and bismuth(Bi), among which 13 elements were quantitative. The top three elements in terms of average content were K&amp;gt;Fe&amp;gt;Na, and the content of B, Na, Al, Ca, Fe, and Ba varied in different batches of Bambusae Concretio Silicea samples from different origins. The correlation coefficient between Ca and Mg was the highest, followed by that between Mn and Zn, both of which showed significant positive correlations. Therefore, it was hypothesized that there was a synergistic incremental relationship between Ca and Mg as well as between Mn and Zn. According to the results of principal component analysis, Fe, As, Ni, Cu, Mn, Na, Mg, Ca, Al, Ba, and B were the main elements of Bambusae Concretio Silicea. According to the results of orthogonal partial least squares-discriminant analysis, Cu, As, and Mn were the common differential elements of three origins, which suggested that the quantitative identification of Cu, As, and Mn could roughly distinguish the three batches of Bambusae Concretio Silicea samples. This study analyzed the elements and their content in different batches of Bambusae Concretio Silicea samples, aiming to provide theoretical support for exploring the pharmacodynamic material basis and mechanism of Bambusae Concretio Silicea and lay a foundation for the quality evaluation, safe application, and resource development and utilization of Bambusae Concretio Silicea.</AbstractText></Abstract><AuthorList CompleteYN="Y"><Author ValidYN="Y"><LastName>Yu</LastName><ForeName>Chun-Xia</ForeName><Initials>CX</Initials><AffiliationInfo><Affiliation>Henan Provincial Center for Drug Evaluation and Inspection Zhengzhou 450000, China.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Kong</LastName><ForeName>Xiang-He</ForeName><Initials>XH</Initials><AffiliationInfo><Affiliation>Beijing University of Chinese Medicine Beijing 102488, China.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Ren</LastName><ForeName>Guang-Xi</ForeName><Initials>GX</Initials><AffiliationInfo><Affiliation>Beijing University of Chinese Medicine Beijing 102488, China.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Xu</LastName><ForeName>Yu-Bin</ForeName><Initials>YB</Initials><AffiliationInfo><Affiliation>Hebei Jujing Pharmaceutical Co., Ltd. Anguo 071200, China.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Jiang</LastName><ForeName>Dan</ForeName><Initials>D</Initials><AffiliationInfo><Affiliation>Beijing University of Chinese Medicine Beijing 102488, China.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Liu</LastName><ForeName>Chun-Sheng</ForeName><Initials>CS</Initials><AffiliationInfo><Affiliation>Beijing University of Chinese Medicine Beijing 102488, China.</Affiliation></AffiliationInfo></Author></AuthorList><Language>chi</Language><PublicationTypeList><PublicationType UI="D004740">English Abstract</PublicationType><PublicationType UI="D016428">Journal Article</PublicationType></PublicationTypeList></Article><MedlineJournalInfo><Country>China</Country><MedlineTA>Zhongguo Zhong Yao Za Zhi</MedlineTA><NlmUniqueID>8913656</NlmUniqueID><ISSNLinking>1001-5302</ISSNLinking></MedlineJournalInfo><ChemicalList><Chemical><RegistryNumber>0</RegistryNumber><NameOfSubstance UI="D014131">Trace Elements</NameOfSubstance></Chemical><Chemical><RegistryNumber>I38ZP9992A</RegistryNumber><NameOfSubstance UI="D008274">Magnesium</NameOfSubstance></Chemical></ChemicalList><CitationSubset>IM</CitationSubset><MeshHeadingList><MeshHeading><DescriptorName UI="D013058" MajorTopicYN="Y">Mass Spectrometry</DescriptorName><QualifierName UI="Q000379" MajorTopicYN="N">methods</QualifierName></MeshHeading><MeshHeading><DescriptorName UI="D014131" MajorTopicYN="N">Trace Elements</DescriptorName><QualifierName UI="Q000032" MajorTopicYN="N">analysis</QualifierName></MeshHeading><MeshHeading><DescriptorName UI="D008274" MajorTopicYN="N">Magnesium</DescriptorName><QualifierName UI="Q000032" MajorTopicYN="N">analysis</QualifierName></MeshHeading></MeshHeadingList><KeywordList Owner="NOTNLM"><Keyword MajorTopicYN="N">Bambusae Concretio Silicea</Keyword><Keyword MajorTopicYN="N">difference</Keyword><Keyword MajorTopicYN="N">inductively coupled plasma-mass spectrometry(ICP-MS)</Keyword><Keyword MajorTopicYN="N">inorganic elements</Keyword></KeywordList></MedlineCitation><PubmedData><History><PubMedPubDate PubStatus="medline"><Year>2024</Year><Month>12</Month><Day>20</Day><Hour>0</Hour><Minute>24</Minute></PubMedPubDate><PubMedPubDate PubStatus="pubmed"><Year>2024</Year><Month>12</Month><Day>20</Day><Hour>0</Hour><Minute>23</Minute></PubMedPubDate><PubMedPubDate PubStatus="entrez"><Year>2024</Year><Month>12</Month><Day>19</Day><Hour>21</Hour><Minute>13</Minute></PubMedPubDate></History><PublicationStatus>ppublish</PublicationStatus><ArticleIdList><ArticleId IdType="pubmed">39701733</ArticleId><ArticleId IdType="doi">10.19540/j.cnki.cjcmm.20240713.103</ArticleId></ArticleIdList></PubmedData></PubmedArticle><PubmedArticle><MedlineCitation Status="MEDLINE" Owner="NLM" IndexingMethod="Automated"><PMID Version="1">38417599</PMID><DateCompleted><Year>2024</Year><Month>03</Month><Day>15</Day></DateCompleted><DateRevised><Year>2024</Year><Month>03</Month><Day>15</Day></DateRevised><Article PubModel="Print-Electronic"><Journal><ISSN IssnType="Electronic">1872-7573</ISSN><JournalIssue CitedMedium="Internet"><Volume>326</Volume><PubDate><Year>2024</Year><Month>May</Month><Day>23</Day></PubDate></JournalIssue><Title>Journal of ethnopharmacology</Title><ISOAbbreviation>J Ethnopharmacol</ISOAbbreviation></Journal><ArticleTitle>Chemical components with antibacterial properties found in sanchen powder from traditional Tibetan medicine.</ArticleTitle><Pagination><StartPage>117981</StartPage><MedlinePgn>117981</MedlinePgn></Pagination><ELocationID EIdType="doi" ValidYN="Y">10.1016/j.jep.2024.117981</ELocationID><ELocationID EIdType="pii" ValidYN="Y">S0378-8741(24)00280-0</ELocationID><Abstract><AbstractText Label="ETHNOPHARMACOLOGICAL RELEVANCE" NlmCategory="BACKGROUND">Sanchen powder is a traditional Tibetan medicine comprising Bambusae Concretio Silicea, Carthami Flos, and Bovis Calculus Artifactus. Bambusae Concretio Silicea is the dried mass of secreted fluid in the stalks of Gramineae plants such as Bambusa textilis McClure or Schizostachyum chinense Rendle. Carthami Flos is the dried flower of Carthamus tinctorius L. in the Compositae plant. Bovis Calculus Artifactus is made from ox bile powder, cholic acid, hyodeoxycholic acid, taurine, bilirubin, cholesterol, and trace elements. Research has evidenced the antibacterial efficacy of Sanchen powder, albeit its active constituents for this effect are yet to be established.</AbstractText><AbstractText Label="AIM OF THE STUDY" NlmCategory="OBJECTIVE">To investigate effective compounds, potential targets, and molecular mechanism of Sanchen powder for its antibacterial properties by using network pharmacology combined with in vitro validation, with the aims of observing the action of effective compounds in Sanchen powder and exploring new therapeutic strategies for antibacterial.</AbstractText><AbstractText Label="MATERIALS AND METHODS" NlmCategory="METHODS">In this study, UPLC-Q-TOF-MS was utilized to identify the chemical composition in Sanchen powder and its blood-borne chemical ingredients post-oral intake. A network pharmacology analysis was used to establish the chemical compound in the blood following oral administration-target-disease network. The study aimed to identify antibacterial active ingredients, which were then subjected to molecular docking and pharmacodynamic experiments to verify their efficacy.</AbstractText><AbstractText Label="RESULTS" NlmCategory="RESULTS">The findings demonstrate that following oral administration, the blood contains seven key components of Sanchen powder, including bilirubin, glycochenodeoxycholic acid, glycocholic acid, taurocholic acid, phenylalanine, safflomin A, and tryptophan. Additionally, the network pharmacology and molecular docking study results indicate the potential antibacterial effects of bilirubin, glycocholic acid, and glycochenodeoxycholic acid. In vitro antibacterial experiments revealed that bilirubin, glycocholic acid, and glycochenodeoxycholic acid could restrict the growth of the Staphylococcus aureus cell membrane at a certain concentration. Moreover, they exhibited antibacterial effects on Staphylococcus aureus, Pseudomonas aeruginosa, Staphylococcus epidermidis, and Escherichia coli.</AbstractText><AbstractText Label="CONCLUSIONS" NlmCategory="CONCLUSIONS">Bilirubin, glycocholic acid, and glycochenodeoxycholic acid could be effective therapeutic ingredients for the antibacterial effects of Sanchen powder. These results offer a foundation for further clinical application and research on the antibacterial effect of Sanchen powder, a Traditional Tibetan Medicine.</AbstractText><CopyrightInformation>Copyright &#xa9; 2024 Elsevier B.V. All rights reserved.</CopyrightInformation></Abstract><AuthorList CompleteYN="Y"><Author ValidYN="Y"><LastName>Zhao</LastName><ForeName>Yueying</ForeName><Initials>Y</Initials><AffiliationInfo><Affiliation>School of Chinese Materia Medica, Beijing University of Chinese Medicine, Beijing, China. Electronic address: ll2820064026@163.com.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Xi</LastName><ForeName>Cheng</ForeName><Initials>C</Initials><AffiliationInfo><Affiliation>School of Chinese Materia Medica, Beijing University of Chinese Medicine, Beijing, China. Electronic address: xichenggjun@163.com.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Liu</LastName><ForeName>Donghan</ForeName><Initials>D</Initials><AffiliationInfo><Affiliation>Beijing Union Pharmaceutical Factory, Beijing, China. Electronic address: liudonghan80@163.com.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Ren</LastName><ForeName>Xiaoqiao</ForeName><Initials>X</Initials><AffiliationInfo><Affiliation>School of Traditional Chinese Medicine, Beijing University of Chinese Medicine, Beijing, China; Institute of Minority Medicine, Beijing University of Chinese Medicine, Beijing, China. Electronic address: rxq23111111@126.com.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Fan</LastName><ForeName>Jiayi</ForeName><Initials>J</Initials><AffiliationInfo><Affiliation>School of Chinese Materia Medica, Beijing University of Chinese Medicine, Beijing, China. Electronic address: fanjiayi050800@163.com.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Tangthianchaichana</LastName><ForeName>Jakkree</ForeName><Initials>J</Initials><AffiliationInfo><Affiliation>Chulabhorn International College of Medicine, Thammasat University, Pathum Thani, Thailand. Electronic address: Jakkreetcm@hotmail.com.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Lu</LastName><ForeName>Yang</ForeName><Initials>Y</Initials><AffiliationInfo><Affiliation>School of Chinese Materia Medica, Beijing University of Chinese Medicine, Beijing, China. Electronic address: landocean28@163.com.</Affiliation></AffiliationInfo></Author><Author ValidYN="Y"><LastName>Wu</LastName><ForeName>Huichao</ForeName><Initials>H</Initials><AffiliationInfo><Affiliation>School of Traditional Chinese Medicine, Beijing University of Chinese Medicine, Beijing, China; Institute of Minority Medicine, Beijing University of Chinese Medicine, Beijing, China. Electronic address: wuhuichao@bucm.edu.cn.</Affiliation></AffiliationInfo></Author></AuthorList><Language>eng</Language><PublicationTypeList><PublicationType UI="D016428">Journal Article</PublicationType></PublicationTypeList><ArticleDate DateType="Electronic"><Year>2024</Year><Month>02</Month><Day>28</Day></ArticleDate></Article><MedlineJournalInfo><Country>Ireland</Country><MedlineTA>J Ethnopharmacol</MedlineTA><NlmUniqueID>7903310</NlmUniqueID><ISSNLinking>0378-8741</ISSNLinking></MedlineJournalInfo><ChemicalList><Chemical><RegistryNumber>0</RegistryNumber><NameOfSubstance UI="D011208">Powders</NameOfSubstance></Chemical><Chemical><RegistryNumber>640-79-9</RegistryNumber><NameOfSubstance UI="D005999">Glycochenodeoxycholic Acid</NameOfSubstance></Chemical><Chemical><RegistryNumber>0</RegistryNumber><NameOfSubstance UI="D000900">Anti-Bacterial Agents</NameOfSubstance></Chemical><Chemical><RegistryNumber>RFM9X3LJ49</RegistryNumber><NameOfSubstance UI="D001663">Bilirubin</NameOfSubstance></Chemical><Chemical><RegistryNumber>0</RegistryNumber><NameOfSubstance UI="D004365">Drugs, Chinese Herbal</NameOfSubstance></Chemical></ChemicalList><CitationSubset>IM</CitationSubset><MeshHeadingList><MeshHeading><DescriptorName UI="D006801" MajorTopicYN="N">Humans</DescriptorName></MeshHeading><MeshHeading><DescriptorName UI="D038861" MajorTopicYN="N">Medicine, Tibetan Traditional</DescriptorName></MeshHeading><MeshHeading><DescriptorName UI="D011208" MajorTopicYN="N">Powders</DescriptorName></MeshHeading><MeshHeading><DescriptorName UI="D062105" MajorTopicYN="N">Molecular Docking Simulation</DescriptorName></MeshHeading><MeshHeading><DescriptorName UI="D005999" MajorTopicYN="N">Glycochenodeoxycholic Acid</DescriptorName></MeshHeading><MeshHeading><DescriptorName UI="D002137" MajorTopicYN="Y">Calculi</DescriptorName></MeshHeading><MeshHeading><DescriptorName UI="D000900" MajorTopicYN="N">Anti-Bacterial Agents</DescriptorName><QualifierName UI="Q000494" MajorTopicYN="N">pharmacology</QualifierName></MeshHeading><MeshHeading><DescriptorName UI="D001663" MajorTopicYN="N">Bilirubin</DescriptorName></MeshHeading><MeshHeading><DescriptorName UI="D004365" MajorTopicYN="Y">Drugs, Chinese Herbal</DescriptorName><QualifierName UI="Q000494" MajorTopicYN="N">pharmacology</QualifierName></MeshHeading></MeshHeadingList><KeywordList Owner="NOTNLM"><Keyword MajorTopicYN="N">Antibacterial effects</Keyword><Keyword MajorTopicYN="N">Bambusae concretio silicea</Keyword><Keyword MajorTopicYN="N">Bovis calculus artifactus</Keyword><Keyword MajorTopicYN="N">Carthami flos</Keyword><Keyword MajorTopicYN="N">Sanchen powder</Keyword></KeywordList><CoiStatement>Declaration of competing interest The authors declare that they have no known competing financial interests or personal relationships that could have appeared to influence the work reported in this paper.</CoiStatement></MedlineCitation><PubmedData><History><PubMedPubDate PubStatus="received"><Year>2023</Year><Month>11</Month><Day>30</Day></PubMedPubDate><PubMedPubDate PubStatus="revised"><Year>2024</Year><Month>2</Month><Day>22</Day></PubMedPubDate><PubMedPubDate PubStatus="accepted"><Year>2024</Year><Month>2</Month><Day>24</Day></PubMedPubDate><PubMedPubDate PubStatus="medline"><Year>2024</Year><Month>3</Month><Day>15</Day><Hour>6</Hour><Minute>44</Minute></PubMedPubDate><PubMedPubDate PubStatus="pubmed"><Year>2024</Year><Month>2</Month><Day>29</Day><Hour>0</Hour><Minute>43</Minute></PubMedPubDate><PubMedPubDate PubStatus="entrez"><Year>2024</Year><Month>2</Month><Day>28</Day><Hour>19</Hour><Minute>16</Minute></PubMedPubDate></History><PublicationStatus>ppublish</PublicationStatus><ArticleIdList><ArticleId IdType="pubmed">38417599</ArticleId><ArticleId IdType="doi">10.1016/j.jep.2024.117981</ArticleId><ArticleId IdType="pii">S0378-8741(24)00280-0</ArticleId></ArticleIdList></PubmedData></PubmedArticle><PubmedArticle><MedlineCitation Status="PubMed-not-MEDLINE" Owner="NLM"><PMID Version="1">37351491</PMID><DateRevised><Year>2024</Year><Month>09</Month><Day>21</Day></DateRevised><Article PubModel="Electronic-eCollection"><Journal><ISSN IssnType="Print">2054-5703</ISSN><JournalIssue CitedMedium="Print"><Volume>10</Volume><Issue>6</Issue><PubDate><Year>2023</Year><Month>Jun</Month></PubDate></JournalIssue><Title>Royal Society open science</Title><ISOAbbreviation>R Soc Open Sci</ISOAbbreviation></Journal><ArticleTitle>The genome of the reef-building glass sponge <i>Aphrocallistes vastus</i> provides insights into silica biomineralization.</ArticleTitle><Pagination><StartPage>230423</StartPage><MedlinePgn>230423</MedlinePgn></Pagination><ELocationID EIdType="pii" ValidYN="Y">230423</ELocationID><ELocationID EIdType="doi" ValidYN="Y">10.1098/rsos.230423</ELocationID><Abstract><AbstractText>Well-annotated and contiguous genomes are an indispensable resource for understanding the evolution, development, and metabolic capacities of organisms. Sponges, an ecologically important non-bilaterian group of primarily filter-feeding sessile aquatic organisms, are underrepresented with respect to available genomic resources. Here we provide a high-quality and well-annotated genome of <i>Aphrocallistes vastus</i>, a glass sponge (Porifera: Hexactinellida) that forms large reef structures off the coast of British Columbia (Canada). We show that its genome is approximately 80 Mb, small compared to most other metazoans, and contains nearly 2500 nested genes, more than other genomes. Hexactinellida is characterized by a unique skeletal architecture made of amorphous silicon dioxide (SiO<sub>2</sub>), and we identified 419 differentially expressed genes between the osculum, i.e. the vertical growth zone of the sponge, and the main body. Among the upregulated ones, mineralization-related genes such as glassin, as well as collagens and actins, dominate the expression profile during growth. Silicateins, suggested being involved in silica mineralization, especially in demosponges, were not found at all in the <i>A. vastus</i> genome and suggests that the underlying mechanisms of SiO<sub>2</sub> deposition in the Silicea <i>sensu stricto</i> (Hexactinellida + Demospongiae) may not be homologous.</AbstractText><CopyrightInformation>&#xa9; 2023 The Authors.</CopyrightInformation></Abstract><AuthorList CompleteYN="Y"><Author ValidYN="Y"><LastName>Francis</LastName><ForeName>Warren R</ForeName><Initials>WR</Initials><Identifier Source="ORCID">0000-0003-3473-4726</Identifier><AffiliationInfo><Affiliation>Department of

In [75]:
df

,drug_name,query,retstart,ids,esearch,efetch_responses
0,silicea,(silicea[Title/Abstract]) AND (pharmacology OR...,0,"[39701733, 38417599, 37351491, 37282866, 36350...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
1,titanium dioxide,(titanium dioxide[Title/Abstract]) AND (pharma...,0,"[41977548, 41976204, 41970853, 41969534, 41945...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
2,ethylhexyl methoxycinnamate,(ethylhexyl methoxycinnamate[Title/Abstract]) ...,0,"[41985167, 41915798, 41548346, 41304479, 41151...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
3,zinc oxide,(zinc oxide[Title/Abstract]) AND (pharmacology...,0,"[41985804, 41984425, 41977622, 41977548, 41976...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
4,povidone-iodine,(povidone-iodine[Title/Abstract]) AND (pharmac...,0,"[41991252, 41905628, 41891504, 41881430, 41871...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
...,...,...,...,...,...,...
1470,l-arginine,(l-arginine[Title/Abstract]) AND (pharmacology...,0,"[41992391, 41989598, 41984173, 41980750, 41977...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
1471,l-ornithine,(l-ornithine[Title/Abstract]) AND (pharmacolog...,0,"[41945138, 41922308, 41904136, 41892305, 41846...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."
1472,throidinum,(throidinum[Title/Abstract]) AND (pharmacology...,0,[],"{'header': {'type': 'esearch', 'version': '0.3...",[]
1473,kaki carbonicum,(kaki carbonicum[Title/Abstract]) AND (pharmac...,0,[],"{'header': {'type': 'esearch', 'version': '0.3...",[]
1474,brimonidine tartrate,(brimonidine tartrate[Title/Abstract]) AND (ph...,0,"[41738452, 41559985, 41305740, 40757513, 40737...","{'header': {'type': 'esearch', 'version': '0.3...","[<?xml version=""1.0"" ?>\n<!DOCTYPE PubmedArtic..."

In [76]:
df = df.drop(columns=['esearch', 'efetch_responses'], errors='ignore')
df = df.explode('ids')
df = df.rename(columns={'ids': 'pmid'})
df['pmid'] = df['pmid'].astype(float)   # or int if df_one is int
df_one['pmid'].dtype

dtype('float64')

In [77]:
df_merged = df_one.merge(df[['pmid', 'drug_name']], on='pmid', how='left')

In [78]:
df_merged.iloc[0]

pmid                                                          39701733.0
title                  [Analysis of inorganic elements in Bambusae Co...
abstract               Inductively coupled plasma mass spectrometry w...
authors                [Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...
journal                Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...
pub_date                                                        2024 Oct
doi                                   10.19540/j.cnki.cjcmm.20240713.103
format                                                        pubmed_xml
source_jsonl_line                                                      1
source_retstart                                                        0
source_efetch_batch                                                    0
drug_name                                                        silicea
Name: 0, dtype: object

In [79]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16252 entries, 0 to 16251
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pmid                 13928 non-null  float64
 1   title                13835 non-null  object
 2   abstract             13417 non-null  object
 3   authors              16252 non-null  object
 4   journal              13928 non-null  object
 5   pub_date             13921 non-null  object
 6   doi                  13787 non-null  object
 7   format               16252 non-null  object
 8   source_jsonl_line    16252 non-null  int64
 9   source_retstart      16252 non-null  int64
 10  source_efetch_batch  16252 non-null  int64
 11  drug_name            16252 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 1.5+ MB

In [80]:
null_cols = df_merged.columns[df_merged.isnull().any()]
df_merged[null_cols].isnull().sum()

pmid        2324
title       2417
abstract    2835
journal     2324
pub_date    2331
doi         2465
dtype: int64

In [81]:
df_merged[df_merged['pmid'].isnull()].head()

,pmid,title,abstract,authors,journal,pub_date,doi,format,source_jsonl_line,source_retstart,source_efetch_batch,drug_name
2994,NaN,None,None,[],None,None,None,medline,274,0,0,....................................purpose su...
2995,NaN,None,None,[],None,None,None,medline,274,0,0,cuprum aceticum
2996,NaN,None,None,[],None,None,None,medline,274,0,0,renes
2997,NaN,None,None,[],None,None,None,medline,274,0,0,helianthemum nummularium flower
2998,NaN,None,None,[],None,None,None,medline,274,0,0,clematis vitalba flower

In [82]:
df_merged = df_merged.dropna(
    subset=['pmid', 'title', 'abstract'],
    how='all'
)

In [83]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13928 entries, 0 to 16251
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   pmid                 13928 non-null  float64
 1   title                13835 non-null  object
 2   abstract             13417 non-null  object
 3   authors              13928 non-null  object
 4   journal              13928 non-null  object
 5   pub_date             13921 non-null  object
 6   doi                  13787 non-null  object
 7   format               13928 non-null  object
 8   source_jsonl_line    13928 non-null  int64
 9   source_retstart      13928 non-null  int64
 10  source_efetch_batch  13928 non-null  int64
 11  drug_name            13928 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 1.4+ MB

In [84]:
df_merged[df_merged['abstract'].isnull()].head()

,pmid,title,abstract,authors,journal,pub_date,doi,format,source_jsonl_line,source_retstart,source_efetch_batch,drug_name
128,41905628.0,"Response to Zhang et al., ""JAAD-D-25-04773R1, ...",None,"[Xu, Jinhui, Geng, Qingwei, Hu, Yong, Liu, Zeh...",Journal of the American Academy of Dermatology,2026 Mar 27,10.1016/j.jaad.2026.03.080,pubmed_xml,5,0,0,povidone-iodine
129,41905628.0,"Response to Zhang et al., ""JAAD-D-25-04773R1, ...",None,"[Xu, Jinhui, Geng, Qingwei, Hu, Yong, Liu, Zeh...",Journal of the American Academy of Dermatology,2026 Mar 27,10.1016/j.jaad.2026.03.080,pubmed_xml,5,0,0,povidone
130,41905628.0,"Response to Zhang et al., ""JAAD-D-25-04773R1, ...",None,"[Xu, Jinhui, Geng, Qingwei, Hu, Yong, Liu, Zeh...",Journal of the American Academy of Dermatology,2026 Mar 27,10.1016/j.jaad.2026.03.080,pubmed_xml,5,0,0,povidone iodine
240,40729015.0,Molecular Mechanisms of,None,"[Yuan, Fahu, Qiao, Yu, Chen, Zhongqiang, He, H...",Current issues in molecular biology,2025 Jul 14,10.3390/cimb47070546,pubmed_xml,14,0,0,lobelia
274,40355111.0,Impact of Homeoprophylactic Arsenicum album 30...,None,"[Nayak, Debadatta, Bhalla, Ruchika, Kaur, Love...",Homeopathy : the journal of the Faculty of Hom...,2026 Feb,10.1055/a-2512-9763,pubmed_xml,17,0,0,arsenicum album

In [85]:
df_merged['pmid'] = df_merged['pmid'].astype(int)
df_merged = df_merged.dropna(subset=['abstract'])
df_merged = df_merged.drop(columns=[
    'source_jsonl_line',
    'source_retstart',
    'source_efetch_batch',
    'format'
])

In [86]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13417 entries, 0 to 16251
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pmid       13417 non-null  int32
 1   title      13339 non-null  object
 2   abstract   13417 non-null  object
 3   authors    13417 non-null  object
 4   journal    13417 non-null  object
 5   pub_date   13411 non-null  object
 6   doi        13279 non-null  object
 7   drug_name  13417 non-null  object
dtypes: int32(1), object(7)
memory usage: 891.0+ KB

In [87]:
df_merged = df_merged.drop_duplicates(subset=['pmid', 'drug_name'])

In [88]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6793 entries, 0 to 16251
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pmid       6793 non-null   int32
 1   title      6735 non-null   object
 2   abstract   6793 non-null   object
 3   authors    6793 non-null   object
 4   journal    6793 non-null   object
 5   pub_date   6787 non-null   object
 6   doi        6709 non-null   object
 7   drug_name  6793 non-null   object
dtypes: int32(1), object(7)
memory usage: 451.1+ KB

In [89]:
df_merged

,pmid,title,abstract,authors,journal,pub_date,doi,drug_name
0,39701733,[Analysis of inorganic elements in Bambusae Co...,Inductively coupled plasma mass spectrometry w...,"[Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2024 Oct,10.19540/j.cnki.cjcmm.20240713.103,silicea
1,39701733,[Analysis of inorganic elements in Bambusae Co...,Inductively coupled plasma mass spectrometry w...,"[Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2024 Oct,10.19540/j.cnki.cjcmm.20240713.103,; silicea
2,39701733,[Analysis of inorganic elements in Bambusae Co...,Inductively coupled plasma mass spectrometry w...,"[Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2024 Oct,10.19540/j.cnki.cjcmm.20240713.103,silicea .
3,38417599,Chemical components with antibacterial propert...,ETHNOPHARMACOLOGICAL RELEVANCE: Sanchen powder...,"[Zhao, Yueying, Xi, Cheng, Liu, Donghan, Ren, ...",Journal of ethnopharmacology,2024 May 23,10.1016/j.jep.2024.117981,silicea
4,38417599,Chemical components with antibacterial propert...,ETHNOPHARMACOLOGICAL RELEVANCE: Sanchen powder...,"[Zhao, Yueying, Xi, Cheng, Liu, Donghan, Ren, ...",Journal of ethnopharmacology,2024 May 23,10.1016/j.jep.2024.117981,; silicea
...,...,...,...,...,...,...,...,...
16247,40660595,Pupillometry changes following ocular administ...,BACKGROUND: This study aimed to assess pupillo...,"[Karakaya, Caner, Kilic, Seyma, Yildirim, Isik]",Medicine,2025 Jul 11,10.1097/MD.0000000000043292,brimonidine tartrate
16248,40193333,Real-Time In Vivo Monitoring of Eye Drop Conce...,The corneal permeability of an eye drop is cru...,"[Ogawa, Risa, Ogata, Genki, Yamagishi, Reiko, ...",ACS sensors,2025 Jun 27,10.1021/acssensors.5c00220,brimonidine tartrate
16249,39055420,Severe Central Nervous System and Respiratory ...,Brimonidine is a third-generation alpha-2 adre...,"[Gul, Faiza, Shah, Mudassir, Waqar, Muhammad, ...",Cureus,2024 Jun,10.7759/cureus.63124,brimonidine tartrate
16250,38936912,Exploring Neuroprotective Effects of Topical B...,BACKGROUND/AIM: Diabetic retinopathy is a lead...,"[Jung, Kyoung In, Kim, Jie Hyun, Han, Jeong-Su...","In vivo (Athens, Greece)",2024,10.21873/invivo.13611,brimonidine tartrate
16251,38874068,Consistent Intraocular Pressure Reduction by S...,Efficient topical drug delivery remains a sign...,"[Huang, Da, Norat, Pedro, Qi, Lin, Chernatynsk...","Advanced science (Weinheim, Baden-Wurttemberg,...",2024 Aug,10.1002/advs.202401648,brimonidine tartrate

In [90]:
import re

df_merged['drug_name'] = (
    df_merged['drug_name']
    .astype(str)
    .str.lower()
    .str.strip()
)
df_merged['drug_name'] = df_merged['drug_name'].str.strip('.,; ')

In [91]:
df_merged['title'] = df_merged['title'].str.strip('.,;[](){}"\' ')

In [92]:
df_merged

,pmid,title,abstract,authors,journal,pub_date,doi,drug_name
0,39701733,Analysis of inorganic elements in Bambusae Con...,Inductively coupled plasma mass spectrometry w...,"[Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2024 Oct,10.19540/j.cnki.cjcmm.20240713.103,silicea
1,39701733,Analysis of inorganic elements in Bambusae Con...,Inductively coupled plasma mass spectrometry w...,"[Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2024 Oct,10.19540/j.cnki.cjcmm.20240713.103,silicea
2,39701733,Analysis of inorganic elements in Bambusae Con...,Inductively coupled plasma mass spectrometry w...,"[Yu, Chun-Xia, Kong, Xiang-He, Ren, Guang-Xi, ...",Zhongguo Zhong yao za zhi = Zhongguo zhongyao ...,2024 Oct,10.19540/j.cnki.cjcmm.20240713.103,silicea
3,38417599,Chemical components with antibacterial propert...,ETHNOPHARMACOLOGICAL RELEVANCE: Sanchen powder...,"[Zhao, Yueying, Xi, Cheng, Liu, Donghan, Ren, ...",Journal of ethnopharmacology,2024 May 23,10.1016/j.jep.2024.117981,silicea
4,38417599,Chemical components with antibacterial propert...,ETHNOPHARMACOLOGICAL RELEVANCE: Sanchen powder...,"[Zhao, Yueying, Xi, Cheng, Liu, Donghan, Ren, ...",Journal of ethnopharmacology,2024 May 23,10.1016/j.jep.2024.117981,silicea
...,...,...,...,...,...,...,...,...
16247,40660595,Pupillometry changes following ocular administ...,BACKGROUND: This study aimed to assess pupillo...,"[Karakaya, Caner, Kilic, Seyma, Yildirim, Isik]",Medicine,2025 Jul 11,10.1097/MD.0000000000043292,brimonidine tartrate
16248,40193333,Real-Time In Vivo Monitoring of Eye Drop Conce...,The corneal permeability of an eye drop is cru...,"[Ogawa, Risa, Ogata, Genki, Yamagishi, Reiko, ...",ACS sensors,2025 Jun 27,10.1021/acssensors.5c00220,brimonidine tartrate
16249,39055420,Severe Central Nervous System and Respiratory ...,Brimonidine is a third-generation alpha-2 adre...,"[Gul, Faiza, Shah, Mudassir, Waqar, Muhammad, ...",Cureus,2024 Jun,10.7759/cureus.63124,brimonidine tartrate
16250,38936912,Exploring Neuroprotective Effects of Topical B...,BACKGROUND/AIM: Diabetic retinopathy is a lead...,"[Jung, Kyoung In, Kim, Jie Hyun, Han, Jeong-Su...","In vivo (Athens, Greece)",2024,10.21873/invivo.13611,brimonidine tartrate
16251,38874068,Consistent Intraocular Pressure Reduction by S...,Efficient topical drug delivery remains a sign...,"[Huang, Da, Norat, Pedro, Qi, Lin, Chernatynsk...","Advanced science (Weinheim, Baden-Wurttemberg,...",2024 Aug,10.1002/advs.202401648,brimonidine tartrate

In [93]:
df_merged.to_csv("ncbi_data.csv", index=False)